BrentLab/harbison_2004:
  dataset:
    harbison_2004:
      carbon_source:
        field: condition
        path: media.carbon_source
      temperature_celsius:
        field: condition
        path: temperature_celsius
BrentLab/kemmeren_2014:
  dataset:
    kemmeren_2014:
      carbon_source:
        path: media.carbon_source
      temperature_celsius:
        path: temperature_celsius
factor_aliases:
  carbon_source:
    galactose:
    - D-galactose
    - Galactose
    - galactose
    glucose:
    - D-glucose
    - dextrose
    - glucose
    raffinose:
    - D-raffinose
    - raffinose
  temperature_celsius:
    heat_shock:
    - 37
    - 39
    standard:
    - 30
